import type { LinearIssue } from "./linear";

export interface CmdRunner {
  /** Run a command in the given cwd. Throws on non-zero exit; throw object exposes `stderr`. */
  run: (cmd: string[], cwd: string) => Promise<{ stdout: string; stderr: string }>;
}

interface CreatePrInput {
  cwd: string;
  branch: string;
  issue: LinearIssue;
  /** Defaults to "main". */
  base?: string;
}

interface CreatePrResult {
  url: string;
  /** Whether a brand-new PR was created (false = a PR already existed). */
  created: boolean;
}

function defaultTitle(issue: LinearIssue): string {
  return `${issue.identifier}: ${issue.title}`;
}

function defaultBody(issue: LinearIssue, branch: string): string {
  return [
    `Auto-generated by Ralph for ${issue.identifier}.`,
    "",
    `Source: ${issue.url}`,
    `Branch: \`${branch}\``,
    "",
    issue.description?.trim() ? `## Description\n\n${issue.description.trim()}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * Push the worktree's branch to origin and open (or surface) a GitHub PR
 * via the `gh` CLI. Returns the PR URL.
 *
 * Behavior:
 * - If the branch has no commits ahead of base, returns null (callers
 *   should treat this as "nothing to PR").
 * - If a PR already exists for the branch, returns its URL with
 *   created=false (idempotent — useful for retries).
 * - All other failures throw with the underlying stderr in the message.
 */
export async function createPullRequest(
  input: CreatePrInput,
  runner: CmdRunner,
): Promise<CreatePrResult | null> {
  const base = input.base ?? "main";

  // Ensure there is something to PR.
  const log = await runner.run(
    ["git", "log", "--oneline", `${base}..HEAD`, "--no-merges"],
    input.cwd,
  );
  if (log.stdout.trim() === "") return null;

  // Push the branch (idempotent with -u).
  await runner.run(["git", "push", "-u", "origin", input.branch], input.cwd);

  // If a PR already exists for this branch, just return its URL.
  const existing = await runner.run(
    [
      "gh",
      "pr",
      "list",
      "--head",
      input.branch,
      "--state",
      "open",
      "--json",
      "url",
      "--jq",
      ".[0].url // empty",
    ],
    input.cwd,
  );
  const existingUrl = existing.stdout.trim();
  if (existingUrl) return { url: existingUrl, created: false };

  const title = defaultTitle(input.issue);
  const body = defaultBody(input.issue, input.branch);
  const created = await runner.run(
    ["gh", "pr", "create", "--base", base, "--title", title, "--body", body],
    input.cwd,
  );
  const url = created.stdout.trim().split("\n").pop() ?? "";
  return { url, created: true };
}
