#!/usr/bin/env bun
// Generate committed Mermaid diagrams of every xstate-mcp machine into
// `docs/state-machines/`. Mirrors the ARCHITECTURE.md generate-and-diff
// pattern: run `bun run build:state-diagrams` to write, and
// `bun run check:state-diagrams:ci` (`--check`) in CI to fail on drift.
//
// Bun-native I/O only (`Bun.write` / `Bun.file`); never `node:fs` sync.
import { exportStateDiagram, inspectMachine } from "@rosneri/xstate-mcp";
import { join } from "node:path";
import { mcpMachineRegistry, type McpMachineEntry } from "../packages/core/src/machines/index.ts";

const repoRoot = join(import.meta.dir, "..");
const docsDir = join(repoRoot, "docs", "state-machines");

const GENERATED_HEADER =
  "<!-- Generated by `bun run build:state-diagrams` — do not edit by hand. -->";

/**
 * Manually-maintained notes appended (outside the generated mermaid block) for
 * specific machines. The exporter only walks `node.events`, so eventless
 * `always` transitions are absent from the diagram; this documents the gap.
 */
const MACHINE_NOTES: Record<string, string> = {
  loop: [
    "## Note: `checkingStop` `always` guards",
    "",
    "The diagram above is generated from each state's `on` transitions. The",
    "`checkingStop` state instead routes via eventless `always` transitions,",
    "which the exporter does not render. For reference, `checkingStop`",
    "evaluates these guards in order and transitions to the first match:",
    "",
    // Columns are pre-aligned to oxfmt's canonical markdown-table width so the
    // pre-commit formatter leaves this generated file untouched (otherwise
    // `--check` would drift against the formatted commit).
    "| Guard                        | Target                        |",
    "| ---------------------------- | ----------------------------- |",
    "| `maxIterationsReached`       | `stopped.maxIterations`       |",
    "| `statusNotActive`            | `stopped.completed`           |",
    "| `costCapReached`             | `stopped.costCap`             |",
    "| `runtimeLimitReached`        | `stopped.runtimeLimit`        |",
    "| `consecutiveFailuresReached` | `stopped.consecutiveFailures` |",
  ].join("\n"),
};

function renderMachineDoc(entry: McpMachineEntry): string {
  const diagram = exportStateDiagram(inspectMachine(entry));
  const parts = [
    GENERATED_HEADER,
    "",
    `# \`${entry.name}\` state machine`,
    "",
    entry.description,
    "",
    "```mermaid",
    diagram,
    "```",
  ];
  const note = MACHINE_NOTES[entry.name];
  if (note) {
    parts.push("", note);
  }
  return parts.join("\n") + "\n";
}

function renderIndex(): string {
  const rows = mcpMachineRegistry.map(
    (entry) => `- [\`${entry.name}\`](./${entry.name}.md) — ${entry.description}`,
  );
  return (
    [
      GENERATED_HEADER,
      "",
      "# State machine diagrams",
      "",
      "Generated Mermaid diagrams for every machine registered with the",
      "project-local xstate-mcp server (`packages/core/src/machines/mcp-registry.ts`).",
      "Run `bun run build:state-diagrams` to regenerate.",
      "",
      ...rows,
    ].join("\n") + "\n"
  );
}

/** Path → desired content, in deterministic registry order. */
function buildOutputs(): Map<string, string> {
  const outputs = new Map<string, string>();
  outputs.set(join(docsDir, "README.md"), renderIndex());
  for (const entry of mcpMachineRegistry) {
    outputs.set(join(docsDir, `${entry.name}.md`), renderMachineDoc(entry));
  }
  return outputs;
}

async function write(outputs: Map<string, string>): Promise<void> {
  for (const [path, content] of outputs) {
    await Bun.write(path, content);
  }
  // eslint-disable-next-line no-console
  console.log(`wrote ${outputs.size} files to ${docsDir}`);
}

async function check(outputs: Map<string, string>): Promise<number> {
  const offending: string[] = [];
  for (const [path, content] of outputs) {
    const file = Bun.file(path);
    const exists = await file.exists();
    if (!exists || (await file.text()) !== content) {
      offending.push(path);
    }
  }
  if (offending.length > 0) {
    // eslint-disable-next-line no-console
    console.error(
      `State-machine diagram drift detected. Run \`bun run build:state-diagrams\` and commit:\n${offending
        .map((p) => `  - ${p}`)
        .join("\n")}`,
    );
    return 1;
  }
  // eslint-disable-next-line no-console
  console.log(`state-machine diagrams in sync (${outputs.size} files)`);
  return 0;
}

async function main(): Promise<void> {
  const outputs = buildOutputs();
  if (process.argv.includes("--check")) {
    process.exit(await check(outputs));
  }
  await write(outputs);
}

await main();
