#!/usr/bin/env bun
/**
 * Generates ARCHITECTURE.md at the repo root from the static feature
 * registry. Drift between source and the generated file is gated in CI by
 * `git diff --exit-code ARCHITECTURE.md`.
 *
 * Run via `bun run build:architecture`.
 */

import { join } from "node:path";
import { registry } from "../features/registry";

interface FeatureSummary {
  id: string;
  ownedSlot: string;
  summary: string;
}

const FEATURE_SUMMARIES: Readonly<Record<string, string>> = {
  confirmation:
    "Gates work behind a plan-ready confirmation comment. Inspects approval/revise replies and unblocks the issue once confirmed.",
  "conflict-fix":
    "Detects PRs with merge conflicts and dispatches a worker to merge base in and resolve.",
  "ci-fix": "Detects PRs whose CI checks have failed and dispatches a worker to fix the failures.",
  implement:
    "Drives the primary build-the-feature loop: spawns a worker for in-progress and todo issues, then records the PR URL.",
  "review-followup":
    "Handles issues that are in the review bucket by addressing reviewer comments and pushing follow-ups.",
  "new-ticket":
    "Promotes mention-triggered tickets that don't have a linked issue yet into a fresh Linear issue.",
  mention:
    "Catch-all for @-mention comments not handled by other slices. Triggers a revise or general reply flow.",
  stuck: "Recovers issues stuck in a non-terminal state by re-attaching the worker or escalating.",
};

function buildFeatureSections(): FeatureSummary[] {
  return registry.map((f) => ({
    id: f.id,
    ownedSlot: f.ownedSlot ?? "(none)",
    summary: FEATURE_SUMMARIES[f.id] ?? "(no summary)",
  }));
}

function render(): string {
  const features = buildFeatureSections();
  const featureBlocks = features
    .map(
      (f) =>
        `### ${f.id}\n\n- **id**: \`${f.id}\`\n- **ownedSlot**: \`${f.ownedSlot}\`\n- **summary**: ${f.summary}\n`,
    )
    .join("\n");

  return [
    "# Ralphy Agent Architecture",
    "",
    "This document is generated from the static feature registry",
    "(`apps/agent/src/features/registry.ts`). Do not edit by hand — run",
    "`bun run build:architecture` to regenerate.",
    "",
    "## Features",
    "",
    featureBlocks,
    "## State machines",
    "",
    "Generated Mermaid diagrams for every machine registered with the",
    "project-local xstate-mcp server live in [`docs/state-machines/`](docs/state-machines/README.md)",
    "(regenerate with `bun run build:state-diagrams`).",
    "",
    "---",
    "",
    "_generated by `bun run build:architecture`_",
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const repoRoot = join(import.meta.dir, "..", "..", "..", "..");
  const out = join(repoRoot, "ARCHITECTURE.md");
  await Bun.write(out, render());
  // eslint-disable-next-line no-console
  console.log(`wrote ${out}`);
}

await main();
