import { findBoundaryViolations } from "@ralphy/workflow/boundaries";
import type { LinearIssue } from "./linear";

export interface CmdRunner {
  /** Run a command in the given cwd. Throws on non-zero exit; throw object exposes `stderr`. */
  run: (cmd: string[], cwd: string) => Promise<{ stdout: string; stderr: string }>;
}

/** Blocker PR this PR is stacked on, surfaced in the PR body. */
export interface StackedOnRef {
  prUrl: string;
  prNumber: number | null;
  blockerIdentifier: string | null;
}

interface CreatePrInput {
  cwd: string;
  branch: string;
  issue: LinearIssue;
  /** Defaults to "main". */
  base?: string;
  /** Globs that mark a file as "meta only" (openspec/, agent-tasks.md, etc.).
   *  When every file in the base..HEAD diff matches one of these, the PR is
   *  blocked instead of opened — the substantive change has been lost. */
  metaOnlyFiles?: string[];
  /** When true, creates the PR as a draft (`--draft`). */
  draft?: boolean;
  /** When this PR is stacked on a blocker's PR (base is the blocker's branch,
   *  not the default base), the blocker PR identity — added to the PR body so
   *  the dependency is clear to reviewers. */
  stackedOn?: StackedOnRef;
}

/**
 * Why a PR was not opened.
 *
 * - `only-meta`: the net diff is meta-only, but the branch's history *did*
 *   touch substantive files — they were created then lost (deleted mid-loop
 *   or absorbed by a merge). The caller should respawn a fix task to restore
 *   them.
 * - `no-op`: the branch never touched a non-meta file across its entire
 *   history. Nothing was lost — the requested work either already exists on
 *   the base branch (done by another change) or was a genuine no-op. The
 *   caller should finalize without a PR rather than respawn a doomed reapply.
 */
type CreatePrBlockedReason = "only-meta" | "no-op";

interface CreatePrResult {
  /** URL of the created/existing PR; null when blocked. */
  url: string | null;
  /** Whether a brand-new PR was created (false = a PR already existed). */
  created: boolean;
  /** When the PR was not opened because of a guard, the reason. */
  blocked?: CreatePrBlockedReason;
  /** When blocked, the list of files that were in the diff (all meta). */
  blockedFiles?: string[];
}

function defaultTitle(issue: LinearIssue): string {
  return `${issue.identifier}: ${issue.title}`;
}

function stackedOnLine(stackedOn: StackedOnRef): string {
  const prRef = stackedOn.prNumber ? `#${stackedOn.prNumber}` : stackedOn.prUrl;
  const ticket = stackedOn.blockerIdentifier ? ` (blocker ${stackedOn.blockerIdentifier})` : "";
  return `> 🥞 Stacked on ${prRef}${ticket} — review/merge that PR first. Base is its branch, not the default branch.`;
}

function defaultBody(issue: LinearIssue, branch: string, stackedOn?: StackedOnRef): string {
  return [
    `Auto-generated by Ralph for ${issue.identifier}.`,
    stackedOn ? stackedOnLine(stackedOn) : "",
    `Source: ${issue.url}`,
    `Branch: \`${branch}\``,
    "",
    issue.description?.trim() ? `## Description\n\n${issue.description.trim()}` : "",
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * List files changed between `<base>` and HEAD. Prefers `origin/<base>` (the
 * remote tip the PR will actually be opened against); falls back to the local
 * `<base>` ref when origin is not fetched.
 */
async function diffFilesAgainstBase(
  runner: CmdRunner,
  cwd: string,
  base: string,
): Promise<string[]> {
  let raw = "";
  try {
    const r = await runner.run(["git", "diff", "--name-only", `origin/${base}...HEAD`], cwd);
    raw = r.stdout;
  } catch {
    try {
      const r = await runner.run(["git", "diff", "--name-only", `${base}...HEAD`], cwd);
      raw = r.stdout;
    } catch {
      return [];
    }
  }
  return raw
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Classify the base..HEAD diff. Returns the file list and whether every
 * file in it matches a meta-only glob (i.e. the substantive change is
 * missing from the branch).
 */
async function classifyDiffAgainstMeta(
  runner: CmdRunner,
  cwd: string,
  base: string,
  metaOnlyFiles: readonly string[],
): Promise<{ files: string[]; onlyMeta: boolean }> {
  const files = await diffFilesAgainstBase(runner, cwd, base);
  if (files.length === 0 || metaOnlyFiles.length === 0) {
    return { files, onlyMeta: false };
  }
  const violations = findBoundaryViolations(files, metaOnlyFiles);
  const metaSet = new Set(violations.map((v) => v.file));
  const onlyMeta = files.every((f) => metaSet.has(f.replace(/\\/g, "/")));
  return { files, onlyMeta };
}

/**
 * Decide whether a meta-only *net diff* is a lost implementation or a genuine
 * no-op, by inspecting the branch's full commit history rather than just the
 * net diff.
 *
 * `git log --name-only base..HEAD` lists every file touched by any commit on
 * the branch. If the branch ever added a substantive (non-meta) file — even
 * one later removed — then real work existed and was lost, so the caller
 * should try to reapply it. If the branch *only ever* touched meta files,
 * nothing was lost: the requested change is already on `base` (landed by a
 * different change) or was a no-op, and reapplying is futile.
 *
 * Returns true ⇒ history is meta-only ⇒ treat as `no-op`. Best-effort: on any
 * git failure it returns false so the caller falls back to the existing
 * "only-meta / reapply" path (the conservative, pre-existing behavior).
 */
async function branchHistoryTouchedOnlyMeta(
  runner: CmdRunner,
  cwd: string,
  base: string,
  metaOnlyFiles: readonly string[],
): Promise<boolean> {
  if (metaOnlyFiles.length === 0) return false;
  let raw = "";
  try {
    const r = await runner.run(
      ["git", "log", "--name-only", "--pretty=format:", `${base}..HEAD`],
      cwd,
    );
    raw = r.stdout;
  } catch {
    return false;
  }
  const touched = Array.from(
    new Set(
      raw
        .split("\n")
        .map((s) => s.trim())
        .filter(Boolean),
    ),
  );
  if (touched.length === 0) return false;
  const metaSet = new Set(findBoundaryViolations(touched, metaOnlyFiles).map((v) => v.file));
  return touched.every((f) => metaSet.has(f.replace(/\\/g, "/")));
}

/**
 * Detect whether the branch's substantive work has already landed on `base`.
 *
 * Two signals — either is sufficient:
 *
 * 1. **`gh pr list --state merged`** — a PR was opened from this branch and
 *    later merged. The most common cause of the "only-meta" false alarm:
 *    the implementation lives on `base` now, the branch only carries
 *    leftover meta files.
 * 2. **`git cherry base HEAD`** — git's own "are these commits already in
 *    base?" check. Every line starting with `-` means the commit is already
 *    in `base` (likely via a squash-merge with a different SHA). When every
 *    line is `-`, the branch contributes no new commits beyond what `base`
 *    has — same conclusion.
 *
 * Either signal returning true means there is nothing left to PR; the loop
 * should exit, not respawn a "reapply lost implementation" fix task.
 */
async function branchAlreadyMerged(
  runner: CmdRunner,
  cwd: string,
  branch: string,
  base: string,
): Promise<boolean> {
  try {
    const r = await runner.run(
      [
        "gh",
        "pr",
        "list",
        "--head",
        branch,
        "--state",
        "merged",
        "--json",
        "number",
        "--jq",
        ".[0].number // empty",
      ],
      cwd,
    );
    if (r.stdout.trim() !== "") return true;
  } catch {
    // gh missing / offline / unauthenticated — fall through to git cherry.
  }

  try {
    const r = await runner.run(["git", "cherry", base, "HEAD"], cwd);
    const lines = r.stdout
      .split("\n")
      .map((s) => s.trim())
      .filter(Boolean);
    if (lines.length > 0 && lines.every((l) => l.startsWith("-"))) return true;
  } catch {
    // Best-effort signal; absence means we cannot prove merged → return false.
  }

  return false;
}

/**
 * Push the worktree's branch to origin and open (or surface) a GitHub PR
 * via the `gh` CLI. Returns the PR URL.
 *
 * Behavior:
 * - If the branch has no commits ahead of base, returns null (callers
 *   should treat this as "nothing to PR").
 * - If the base..HEAD diff contains only meta files (openspec, tasks.md,
 *   etc.), returns `{ url: null, created: false, blocked: "only-meta",
 *   blockedFiles }` without pushing or calling `gh` — the substantive
 *   change has been lost and the caller must re-run the worker.
 * - If a PR already exists for the branch, returns its URL with
 *   created=false (idempotent — useful for retries).
 * - All other failures throw with the underlying stderr in the message.
 */
export async function createPullRequest(
  input: CreatePrInput,
  runner: CmdRunner,
): Promise<CreatePrResult | null> {
  const base = input.base ?? "main";

  // Ensure there is something to PR.
  const log = await runner.run(
    ["git", "log", "--oneline", `${base}..HEAD`, "--no-merges"],
    input.cwd,
  );
  if (log.stdout.trim() === "") return null;

  // Substantive-diff guard. If every changed file matches a meta glob,
  // the implementation has been lost (either deleted mid-loop or merged
  // upstream) — refuse to push an empty PR. Distinguish "merged upstream"
  // from "lost": when a prior PR for this branch is already merged, the
  // substantive work is on `base` and there is genuinely nothing left to
  // open; treat it as "nothing to PR" rather than a blocked failure that
  // triggers a fix-task respawn.
  const metaOnlyFiles = input.metaOnlyFiles ?? [];
  if (metaOnlyFiles.length > 0) {
    const classification = await classifyDiffAgainstMeta(runner, input.cwd, base, metaOnlyFiles);
    if (classification.onlyMeta && classification.files.length > 0) {
      if (await branchAlreadyMerged(runner, input.cwd, input.branch, base)) {
        return null;
      }
      // Distinguish "lost implementation" (history had real code) from a
      // genuine no-op (branch only ever touched meta files — the work is
      // already on base or was never needed). The latter must not trigger a
      // doomed reapply loop.
      const historyOnlyMeta = await branchHistoryTouchedOnlyMeta(
        runner,
        input.cwd,
        base,
        metaOnlyFiles,
      );
      return {
        url: null,
        created: false,
        blocked: historyOnlyMeta ? "no-op" : "only-meta",
        blockedFiles: classification.files,
      };
    }
  }

  // Push the branch (idempotent with -u).
  await runner.run(["git", "push", "-u", "origin", input.branch], input.cwd);

  // If a PR already exists for this branch, just return its URL.
  const existing = await runner.run(
    [
      "gh",
      "pr",
      "list",
      "--head",
      input.branch,
      "--state",
      "open",
      "--json",
      "url",
      "--jq",
      ".[0].url // empty",
    ],
    input.cwd,
  );
  const existingUrl = existing.stdout.trim();
  if (existingUrl) return { url: existingUrl, created: false };

  const title = defaultTitle(input.issue);
  const body = defaultBody(input.issue, input.branch, input.stackedOn);
  const createArgs = ["gh", "pr", "create", "--base", base, "--title", title, "--body", body];
  if (input.draft) createArgs.push("--draft");
  const created = await runner.run(createArgs, input.cwd);
  const url = created.stdout.trim().split("\n").pop() ?? "";
  return { url, created: true };
}
